---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: secretconfigs.config.knime.com
spec:
  group: config.knime.com
  names:
    kind: SecretConfig
    listKind: SecretConfigList
    plural: secretconfigs
    singular: secretconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SecretConfig is the Schema for the secretconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SecretConfigSpec defines the desired state of SecretConfig
            properties:
              sourceNamespace:
                type: string
              sourceSecretName:
                type: string
              targetNamespace:
                type: string
              targetSecretData:
                additionalProperties:
                  type: string
                type: object
              targetSecretName:
                type: string
              targetSecretType:
                type: string
            required:
            - sourceNamespace
            - sourceSecretName
            - targetNamespace
            - targetSecretData
            - targetSecretName
            type: object
          status:
            description: SecretConfigStatus defines the observed state of SecretConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
