## Values file for ingress-nginx helm chart
## Find all options and full documentation here: https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

controller:
  config:
    proxy-body-size: 0
    proxy-connect-timeout: 60
    proxy-read-timeout: 1800
    proxy-send-timeout: 1800
    use-forwarded-headers: true
  image:
    digest: false
  ingressClass: business-hub
  ingressClassResource:
    name: business-hub
  service:
    ## Specifying type `NodePort` which can be used when
    ## deploying Ingress-Nginx to a local cluster for testing.
    type: NodePort
    targetPorts:
      http: http
      https: http